// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inefmnoyugeuuagpcysx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImluZWZtbm95dWdldXVhZ3BjeXN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3Nzk4NzcsImV4cCI6MjA2NDM1NTg3N30.8DVbr-VrT33J2b4gp2_qWwOfweR8400g1bCatxG0z-U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);